### ISSUE TITLE
Unable to get deno-dash-compiler to compile to com.mojang

### ISSUE THREAD

**Issue by FrederoxDev** [bridge-core/deno-dash-compiler#1]
When I run `dash_compiler build --mode development` it still seems to build in `project folder\builds\dist\project name`

https://user-images.githubusercontent.com/69014593/177403287-3be77daa-e1b2-46f3-888b-ee1a1bf32ab4.mp4

- I have tried uninstalling and reinstalling the package

**Comment by solvedDev** [comment]
There's currently an issue with the deno registry (it didn't push out our latest updates). For now, you can install dash via this command instead: `deno install --reload -A -f -n dash_compiler https://raw.githubusercontent.com/bridge-core/deno-dash-compiler/main/mod.ts`

Please report back whether syncing works afterwards

**Comment by FrederoxDev** [comment]
Yep, now it compiles👍 

Also is it possible to compile to the com.mojang folder for the preview edition of Minecraft?

**Comment by solvedDev** [comment]
Yes, you can configure the folder with the `--out` argument already. We can probably make compiling to the Minecraft Preview easier than that though. Mind creating a new issue for this request? Thank you!
